logging:
  level:
    root: INFO
    org.springframework.web.socket: WARN
    org.apache.hc.client5.http.wire: WARN
    org.atmosphere.cpr.AtmosphereFramework: WARN
    com.sap.demo: DEBUG

app:
  data:
    generate-seed: 100
    generate-items: 40